### ISSUE TITLE
Feature Suggestion: Have sort mode stay at previous setting between menus

### ISSUE THREAD

**Issue by bloodcloak** [chrislee0419/EnhancedSearchAndFilters#11]
It is quite annoying as a mapper when switching between the Custom Songs pack and the WIP pack during testing and having to activate the sort mode to newest every single time. 

Could it be persistent such that it remembers the previous sort mode between switches of the albums? So in my case maps are always sorted by newest even if I switch to a different album or playlist.
This would apply not just for newest but the mode of newest and have this apply to the default/playcount option as well. 

If possible could it also remember the previous album and song selected between the song selection, main menu, and restarts?

This is the only gripe I have with this mod compared to songbrowser. Keep up the great work!

**Comment by chrislee0419** [comment]
Persistent sort mode when switch level packs seems like it should be something simple to do. Only reason I had it turn back to default was because it would have been consistent with how filters work, but I guess it doesn't have to be that way.

Remembering previous level pack and selected song shouldn't be too hard to implement either.

I'll take a look at it once I'm done fixing up some other stuff.
