### ISSUE TITLE
[Feature Request] Score attained filter

### ISSUE THREAD

**Issue by Ghost---Shadow** [chrislee0419/EnhancedSearchAndFilters#20]
I know a similar idea is being discussed over here #18 but this is slightly easier.

*As a user, I want to know all the Expert/Expert+ levels where I have not scored a `SS` rank yet.*

It will be a two step process
* The user will use the existing difficulty filter to filter by Expert/Expert+ songs
* The user will then use a score achieved filter to filter all songs by achieved scores regardless of difficulty

The intersection of these two results will give the desired result.

No rank, i.e. never completed should also be a valid option.

**Comment by chrislee0419** [comment]
Hey Ghost---Shadow, thanks for the suggestion! That appears to be mostly doable. The only issue I see is that "regardless of difficulty" part. 

Suppose the difficulty filter has been configured to only allow beatmaps that have the Expert or Expert+ difficulties available and the proposed score achieved filter has been configured to look for beatmaps where the highest rank achieved is an A or below on **any** difficulty. The filter would include beatmaps where the user scored an A on Hard, but SS on Expert/Expert+ (this could happen if the user has friends that played the Hard difficulty whereas the user only plays the Expert/Expert+ difficulties or the beatmap is old and the last time the Hard difficulty was played was when the user was much less skilled).

Likewise, if the score achieved filter was configured to look for beatmaps where the highest rank achieved is an A or below on **all** difficulties, then beatmaps where the user scored an SS on Hard, but A on Expert/Expert+ will not be included.

There's two potential solutions that I can see: integrate difficulty into the score achieved filter (much like how the NJS and Player Stats [full combo and/or completion] filters currently work) or make filters aware of each other's settings (currently, all filters are completely independent from each other).

At this point, I might just make it possible for filters to read each other's settings, since, from a user experience standpoint, that is much easier to use. I'm actually a bit surprised I haven't though about that before. This would solve the issue by having the achieved score filter only check difficulties that will pass the difficulty filter (and if the difficulty filter is inactive, check the score for all difficulties).

About having no rank being an option, I don't think that should be necessary, since the Player Stats filter already includes a completion setting.

**Comment by Ghost---Shadow** [comment]
Yeah, you are right, it needs to know the rank achieved for each difficulty. My bad.

**Comment by chrislee0419** [comment]
Included in the [v2.3.4](https://github.com/chrislee0419/EnhancedSearchAndFilters/releases/tag/v2.3.4) release.
