### ISSUE TITLE
Any Plans for BS 1.6.0 ?

### ISSUE THREAD

**Issue by Bootscreen** [chrislee0419/EnhancedSearchAndFilters#6]
Hey,

have you any Plans on Updating this for BS 1.6.0 ?

**Comment by chrislee0419** [comment]
Yup, although it is going to take longer than usual to update. The library I was originally using for the user interface ([CustomUI](https://github.com/beat-saber-modding-group/BeatSaber-CustomUI)) is now deprecated, being replaced by [BSML](https://github.com/monkeymanboy/BeatSaberMarkupLanguage).

I'm still in the process of learning BSML and there are a lot of user interface elements in this mod, hence why it is going to take some time to get this working for 1.6.0.

Additionally, I'm going to have to see what's going on with BeatSaverDownloader when it gets updated, since this mod interacts with some of the UI in that mod.

**Comment by chrislee0419** [comment]
Finally finished updating the mod. Although I wasn't able to get it finished for 1.6.0, the newest version should work for 1.6.1 (and 1.6.2).
