### ISSUE TITLE
Doesn't change anything

### ISSUE THREAD

**Issue by DanDon** [chrislee0419/EnhancedSearchAndFilters#7]
On game version 1.6.2 with all required dependencies installed but nothing shows up anywhere in beat saber for this mod.

Except in mod settings to check whether to disable Search or filters but they are not ticked

**Comment by chrislee0419** [comment]
Hi, can you send a copy of your log to me?
You can find it at 'Beat Saber/Logs/_latest.log'

**Comment by DanDon** [comment]
Ah no it's okay. I can see it now. It is only available on songs already in the game and not for searching in the 'more songs' section from the internet. 
It also only searches songs in the game and not custom songs. Also the compact view is the only thing that allows you to type on the keyboard. The noncompact view overlaps the enter and space and only clicks on numbers and none of the letters.

**Comment by chrislee0419** [comment]
The button panel shouldn't be only showing up for built-in songs; it should display whenever you are in the solo-free play or party play modes. Does the button panel just disappear when switching from a built-in songs level pack to the custom level pack?

Also, can you still provide your log to me (any pictures would also be helpful as well)?
It sounds like there's an issue with initialization in the search screen that might hint at a mod incompatibility or something else, since I'm not seeing any of the issues you are encountering.

**Comment by chrislee0419** [comment]
There hasn't been a follow-up on what was reported, which seems like incorrect behaviour by the mod and I haven't received any logs to verify, so I assume this is no longer an issue.
