### ISSUE TITLE
Min and Max star filter is extremely sensitive

### ISSUE THREAD

**Issue by Blenderpics** [chrislee0419/EnhancedSearchAndFilters#9]
When using the min/max star filter, i am not really able to edit the default limit of those filters.
One single click on the up/down button right to the value increases/decreases that value by a huge amount.
It jumps from the default value of 3.0 straight to 15.0.

**Comment by chrislee0419** [comment]
Well, that's really weird. I'm not seeing that issue on my side (it should have incremented in steps of 0.25).

Do you mind sending over your latest log file so I can check if there's any errors being produced? You can find it at `Beat Saber\Logs\_latest.log`.

**Comment by Blenderpics** [comment]
I just tested it again. It actually jumps from 3.0 straight to 28.0.
So its a 25.0 increment each time i press the up or down button.
Since the correct increment value is a tens potency, i just might know why this issue occurs.

I am german. my windows therfore is set to the german locale, which includes the european number format. That means a "." is used as a thousands separator and a "," is used as a decimal separator.

.NET (and i guess mono) uses the OS dependent number format for parsing, if you don't specifically speficy a fixed format. A `float.Parse("2.5")` therefore returns 25 instead of 2.5.

[_latest.log](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/4208904/_latest.log)
![Beat Saber 2020 02 15 - 19 47 40 01-1 (2)](https://user-images.githubusercontent.com/1348725/74593752-fc4f6200-502e-11ea-92f7-719e2a43449b.gif)

**Comment by chrislee0419** [comment]
I think you might be right that it's a locale issue. I've taken a look at it in my mod and in BSML (since those settings are generated using BSML) and it turns out BSML might be converting floats/doubles to strings differently depending on locale. But later on, when it parses those strings back to floats/doubles, it does it using CultureInfo.CultureInvariant (which parses it with '.' representing the decimal according to [this stack overflow answer](https://stackoverflow.com/a/24375316)).

I think I've got it fix, but I'll need your help to validate it. Can you download this modified copy of BSML and see if it fixes the issue? If it works for you, I'll send in a PR for the fix to the BSML repo.

[BSML.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/4209072/BSML.zip)

**Comment by Blenderpics** [comment]
It works with your patched BSML dll.
looks like that did the trick.
Thanks!

I guess i have to wait until your patch gets merged.
Can you give me a link to your pull request?

**Comment by chrislee0419** [comment]
Awesome! Great to see that it fixed it. Thanks for reporting the issue and helping me test it.

Here's the [pull request I made for this issue in the BSML repo](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/pull/22).

**Comment by Blenderpics** [comment]
Since the Pull Request got merged, i am going to close this issue.
Thanks!
